"""empty message

Revision ID: 74ddabdd664b
Revises: 
Create Date: 2024-07-29 22:27:17.750703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ddabdd664b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('friend_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('friend_name', sa.String(length=20), nullable=False),
    sa.Column('timetable', sa.JSON(), nullable=True),
    sa.Column('timing', sa.DATE(), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('other', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('friend_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('friend_id_list', sa.JSON(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('friends')
    # ### end Alembic commands ###
